$schema: https://raw.githubusercontent.com/streetsidesoftware/cspell/main/cspell.schema.json
version: '0.2'
ignorePaths:
  - .git
  - cspell.config.yaml
  - python/envs
  - tex/output
  - setups/private-tools
  - setups/fasd
  - users
words:
  - Ikok
  - Karabiner
  - SAVEHIST
  - Shougo
  - Townk
  - Ulti
  - WORDCHARS
  - Waka
  - Yggdroot
  - actionformats
  - aiofiles
  - aiplatform
  - ambiwidth
  - asyncomplete
  - augroup
  - autocmd
  - autoselect
  - backslach
  - batchmode
  - bblencoding
  - beautifulsoup
  - benchvimrc
  - biber
  - bibtex
  - bindkey
  - blocklist
  - cespare
  - cmdheight
  - colorcolumn
  - compinit
  - completeopt
  - completor
  - conceallevel
  - cterm
  - ctermbg
  - ctermfg
  - cursorline
  - dein
  - displayline
  - dups
  - dvipdf
  - dvipdfmx
  - elzr
  - expandtab
  - fasd
  - fastapi
  - fastforward
  - fenc
  - fnamemodify
  - foldmethod
  - fpath
  - frecency
  - frontmost
  - ftdetect
  - ftplugin
  - hashivim
  - hatpos
  - hatsunemiku
  - hdbscan
  - hlsearch
  - hoge
  - honza
  - httpx
  - ignorecase
  - ikokpro
  - imap
  - incsearch
  - inoremap
  - isdirectory
  - isort
  - jopen
  - junegunn
  - jupyterlog
  - kamykn
  - karabiner
  - karakuri
  - keybind
  - langserver
  - laststatus
  - latexmk
  - latexmkrc
  - lervag
  - lightgbm
  - lightline
  - listchars
  - liuchengxu
  - lxml
  - matchtime
  - matplotlib
  - mattn
  - mendex
  - menuone
  - mktexlsr
  - mojimoji
  - mypy
  - nanotech
  - nbextension
  - nbextensions
  - nbsp
  - nerdtree
  - nmap
  - nnoremap
  - nocursorline
  - nodebrew
  - nonomatch
  - nonstopmode
  - noremap
  - nospell
  - numba
  - numpy
  - onemore
  - openbrowser
  - openpyxl
  - outputter
  - paperist
  - pbibtex
  - pdfdvi
  - pipenv
  - pipx
  - plasticboy
  - platex
  - popupmenu
  - powerline
  - prabirshrestha
  - precmd
  - pumheight
  - pumvisible
  - pwgen
  - pydantic
  - pyenv
  - pyls
  - pytest
  - quickrun
  - runtimepath
  - safechars
  - scikit
  - scipy
  - scrooloose
  - seaborn
  - setaf
  - setlocal
  - setopt
  - shellcmdflag
  - shiftwidth
  - showmatch
  - smartcase
  - smartindent
  - smarttab
  - snfv
  - softtabstop
  - spelllang
  - stagedstr
  - starlette
  - statusline
  - streamlit
  - sudachidict
  - sudachipy
  - synctex
  - tabline
  - termwinsize
  - texlab
  - texlive
  - texmf
  - thinca
  - timeoutlen
  - toplevel
  - tpope
  - tqdm
  - ttimeoutlen
  - ttymouse
  - tyru
  - ultisnips
  - umap
  - undodir
  - undofile
  - unstagedstr
  - uvicorn
  - venv
  - vimrc
  - vimtex
  - vimundo
  - virtualedit
  - virtualtext
  - visualbell
  - vmap
  - vnoremap
  - wakatime
  - whichwrap
  - wildmenu
  - wildoptions
  - wrapscan
  - xgboost
  - xlrd
  - xlwt
  - xvfz
  - zeropos
  - zstyle
