[[plugins]]
repo = 'cespare/vim-toml'
on_ft = ['toml']


[[plugins]]
repo = 'lervag/vimtex'
on_ft = ['tex']
hook_add = '''
let g:vimtex_compiler_latexmk_engines = { '_' : '-pdfdvi' }
let g:vimtex_compiler_latexmk = {
     \ 'background': 1,
     \ 'build_dir': '',
     \ 'continuous': 1,
     \ 'executable': 'latexmk',
     \ 'options': [
     \    '-pdfdvi', 
     \    '-verbose',
     \    '-file-line-error',
     \    '-synctex=1',
     \    '-interaction=nonstopmode',
     \],
     \}
let g:vimtex_view_general_viewer
     \ = '/Applications/Skim.app/Contents/SharedSupport/displayline'
let g:vimtex_view_general_options = '-r @line @pdf @tex'
autocmd FileType tex syntax spell toplevel
let g:vimtex_compiler_latexmk['callback'] = 0 "callbackの警告を表示しない
let g:vimtex_complete_enabled = 0
'''


[[plugins]]
repo = 'plasticboy/vim-markdown'
on_ft = ['md', 'markdown']
hook_add = '''
" リストの末尾で改行(Enter)したときにリスト化しない
" let g:vim_markdown_auto_insert_bullets = 0
" Shift-o でinsertモードに入ったときに自動インデントしない
let g:vim_markdown_new_list_item_indent = 0
let g:vim_markdown_conceal = 0
let g:vim_markdown_folding_disabled = 1
'''


[[plugins]]
repo = 'elzr/vim-json'
on_ft = ['json']
hook_add = '''
let g:vim_json_syntax_conceal = 0
'''


[[plugins]]
repo = 'hashivim/vim-terraform'
on_ft = ['tf', 'terraform']
hook_add = '''
let g:terraform_align=1
let g:terraform_fmt_on_save=1
'''


[[plugins]]
repo = 'mechatroner/rainbow_csv'
on_ft = ['csv']


[[plugins]]
repo = 'mattn/vim-corona-stats'
on_ft = ['txt']
