[[plugins]]
repo = 'cespare/vim-toml'
on_ft = ['toml']

[[plugins]]
repo = 'othree/yajs.vim'
on_ft = ['javascript']

[[plugins]]
repo = 'mattn/emmet-vim'
on_ft = ['css', 'html', 'javascript']

[[plugins]]
repo = 'marijnh/tern_for_vim'
on_ft = ['javascript']
# npm installの必要あり

# [[plugins]]
# repo = 'pangloss/vim-javascript'
# on_ft = ['javascript']
# hook_add = '''
# let g:javascript_plugin_flow = 1
# '''

[[plugins]]
repo = 'plasticboy/vim-markdown'
on_ft = ['md', 'markdown']

[[plugins]]
repo = 'kannokanno/previm'
on_ft = ['md', 'markdown']
hook_add = '''
nnoremap <silent> <C-o> :PrevimOpen<CR> " Ctrl-oでプレビュー
" 自動で折りたたまないようにする
let g:vim_markdown_folding_disabled=1
let g:previm_enable_realtime = 1
'''

# ===== Games =====
[[plugins]]
repo = 'rbtnn/game_engine.vim'
on_ft = ['text']

[[plugins]]
repo = 'rbtnn/puyo.vim'
on_ft = ['text']

[[plugins]]
repo = 'rbtnn/mario.vim'
on_ft = ['text']

[[plugins]]
repo = 'vim-scripts/TeTrIs.vim'
on_ft = ['text']

