[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/neocomplete.vim'

[[plugins]]
repo = 'Shougo/neosnippet.vim'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 'lervag/vimtex'

[[plugins]]
repo = 'thinca/vim-quickrun'

[[plugins]]
repo = 'tyru/caw.vim'

#[[plugins]]
#repo = 'mattn/emmet-vim'

[[plugins]]
repo = 'pangloss/vim-javascript'

[[plugins]]
repo = 'marijnh/tern_for_vim'

[[plugins]]
repo = 'kannokanno/previm'

[[plugins]]
repo = 'tyru/open-browser.vim'

#[[plugins]]
#repo = 'ctrlpvim/ctrlp.vim'

#[[plugins]]
#repo = 'scrooloose/syntastic'

#[[plugins]]
#repo = 'davidhalter/jedi-vim'

