[[plugins]]
repo = 'Shougo/dein.vim'


[[plugins]]
repo = 'Shougo/neocomplete.vim'
hook_add = '''
" Vim起動時にneocompleteを有効にする
let g:neocomplete#enable_at_startup = 1
" smartcase有効化. 大文字が入力されるまで大文字小文字の区別を無視する
let g:neocomplete#enable_smart_case = 1
" 3文字以上の単語に対して補完を有効にする
let g:neocomplete#min_keyword_length = 2
" 区切り文字まで補完する
let g:neocomplete#enable_auto_delimiter = 1
" 1文字目の入力から補完のポップアップを表示
let g:neocomplete#auto_completion_start_length = 1
" バックスペースで補完のポップアップを閉じる
inoremap <expr><BS> neocomplete#smart_close_popup()."<C-h>"

" エンターキーで補完候補の確定. スニペットの展開もエンターキーで確定
imap <expr><CR> neosnippet#expandable() ?
	\ "<Plug>(neosnippet_expand_or_jump)" :
	\ pumvisible() ? "<C-y>" : "<CR>"
" タブキーで補完候補の選択. スニペット内のジャンプもタブキーでジャンプ
imap <expr><TAB> pumvisible() ?
	\ "<C-n>" : 
	\ neosnippet#jumpable() ?
	\ "<Plug>(neosnippet_expand_or_jump)" :
	\ "<TAB>"
'''


[[plugins]]
repo = 'Shougo/neosnippet.vim'


[[plugins]]
repo = 'Shougo/neosnippet-snippets'


[[plugins]]
repo = 'tpope/vim-fugitive'


[[plugins]]
repo = 'scrooloose/nerdtree'
hook_add = '''
nnoremap <silent><Space>f :NERDTreeToggle<CR>
'''


[[plugins]]
repo = 'thinca/vim-quickrun'
hook_add = '''
let g:quickrun_config = {
\   'outputter/buffer/split': ':right 1sp'
\ }
nnoremap <expr><silent> <C-c> quickrun#is_running()
\ ? quickrun#sweep_sessions() : "\<C-c>"
'''


[[plugins]]
repo = 'tyru/caw.vim'
hook_add = '''
" 行の最初の文字の前にコメント文字をトグル
nmap <C-i> <Plug>(caw:hatpos:toggle)
vmap <C-i> <Plug>(caw:hatpos:toggle)
" 行頭にコメントをトグル
nmap <Leader>c <Plug>(caw:zeropos:toggle)
vmap <Leader>c <Plug>(caw:zeropos:toggle)
'''


[[plugins]]
repo = 'tyru/open-browser.vim'
hook_add = '''
nmap gl <Plug>(openbrowser-smart-search)
vmap gl <Plug>(openbrowser-smart-search)
'''



# ===== 使わなくなったプラグイン =====
# [[plugins]]
# repo = 'ctrlpvim/ctrlp.vim'


# [[plugins]]
# repo = 'scrooloose/syntastic'
# hook_add = '''
# "let g:syntastic_python_checkers = ['pyflakes', 'pep8']
# "let g:syntastic_python_checkers = ['flake8']
# '''


# [[plugins]]
# repo = 'davidhalter/jedi-vim'

