[[plugins]]
repo = 'cespare/vim-toml'
on_ft = ['toml']



[[plugins]]
repo = 'plasticboy/vim-markdown'
on_ft = ['md', 'markdown']
hook_add = '''
" リストの末尾で改行(Enter)したときにリスト化しない
" let g:vim_markdown_auto_insert_bullets = 0
" Shift-o でinsertモードに入ったときに自動インデントしない
let g:vim_markdown_new_list_item_indent = 0
let g:vim_markdown_conceal = 0
'''


[[plugins]]
repo = 'kannokanno/previm'
on_ft = ['md', 'markdown']
hook_add = '''
nnoremap <silent> <C-o> :PrevimOpen<CR> " Ctrl-oでプレビュー
" 自動で折りたたまないようにする
let g:vim_markdown_folding_disabled=1
let g:previm_enable_realtime = 1
'''
# 数式を表示するためにソースに追加書き込みが必要


[[plugins]]
repo = 'elzr/vim-json'
on_ft = ['json']
hook_add = '''
let g:vim_json_syntax_conceal = 0
'''

# [[plugins]]
# repo = 'ryanolsonx/vim-lsp-python'
# on_ft = ['python']
# hook_add = '''
# " registar pyls to vim-lsp
# let s:pyls_path = '~/Settings/python-settings/complete/bin/pyls'
# if (executable(expand(s:pyls_path)))
#     au User lsp_setup call lsp#register_server({
#     \ 'name': 'pyls',
#     \ 'cmd': {server_info->[expand(s:pyls_path)]},
#     \ 'whitelist': ['python']
#     \ })
# endif
# '''
