[[plugins]]
repo = 'Shougo/dein.vim'


[[plugins]]
repo = 'Shougo/neocomplete.vim'
hook_add = '''
" Vim起動時にneocompleteを有効にする
let g:neocomplete#enable_at_startup = 1
" smartcase有効化. 大文字が入力されるまで大文字小文字の区別を無視する
let g:neocomplete#enable_smart_case = 1
" 3文字以上の単語に対して補完を有効にする
let g:neocomplete#min_keyword_length = 2
" 区切り文字まで補完する
let g:neocomplete#enable_auto_delimiter = 1
" 1文字目の入力から補完のポップアップを表示
let g:neocomplete#auto_completion_start_length = 1
" バックスペースで補完のポップアップを閉じる
inoremap <expr><BS> neocomplete#smart_close_popup()."<C-h>"

" エンターキーで補完候補の確定. スニペットの展開もエンターキーで確定
imap <expr><CR> neosnippet#expandable() ?
	\ "<Plug>(neosnippet_expand_or_jump)" :
	\ pumvisible() ? "<C-y>" : "<CR>"
" タブキーで補完候補の選択. スニペット内のジャンプもタブキーでジャンプ
imap <expr><TAB> pumvisible() ?
	\ "<C-n>" : 
	\ neosnippet#jumpable() ?
	\ "<Plug>(neosnippet_expand_or_jump)" :
	\ "<TAB>"
'''



[[plugins]]
repo = 'Shougo/neosnippet.vim'


[[plugins]]
repo = 'Shougo/neosnippet-snippets'


[[plugins]]
repo = 'scrooloose/nerdtree'
hook_add = '''
nnoremap <silent><Space>f :NERDTreeToggle<CR>
'''


[[plugins]]
repo = 'thinca/vim-quickrun'
hook_add = '''
let g:quickrun_config = {
\   'outputter/buffer/split': ':right 1sp'
\ }
nnoremap <expr><silent> <C-c> quickrun#is_running()
\ ? quickrun#sweep_sessions() : "\<C-c>"
'''


[[plugins]]
repo = 'tyru/caw.vim'
hook_add = '''
" ファイルタイプの自動検出を一旦offにする
" deinを使ったときにcaw.vimがうまく機能しなかったときにこれで直った
" (参考URL) http://d.hatena.ne.jp/wiredool/20120618/1340019962
filetype off
filetype plugin indent off

" 行の最初の文字の前にコメント文字をトグル
nmap <C-i> <Plug>(caw:hatpos:toggle)
vmap <C-i> <Plug>(caw:hatpos:toggle)
" 行頭にコメントをトグル
nmap <Leader>c <Plug>(caw:zeropos:toggle)
vmap <Leader>c <Plug>(caw:zeropos:toggle)

" ファイルタイプの自動検出を有効にする
filetype plugin indent on
'''


[[plugins]]
repo = 'tyru/open-browser.vim'
hook_add = '''
nmap gl <Plug>(openbrowser-smart-search)
vmap gl <Plug>(openbrowser-smart-search)
'''


[[plugins]]
repo = 'vim-scripts/autodate.vim'
hook_add = '''
let g:autodate_format="%Y/%m/%d %H:%M:%S %Z"
'''

[[plugins]]
repo = 'Townk/vim-autoclose'
hook_add='''
let g:AutoCloseProtectedRegions = ["Character"]
'''
# pythonで' "がうまく動かない?
# let g:AutoClosePairs = "() {} [] \" \'"
#


[[plugins]]
repo = 'vim-airline/vim-airline'
depends = ['vim-airline-themes']
hook_add = '''
let g:airline#extensions#tabline#enabled = 1
let g:airline#extensions#default#layout = [
\ ['a', 'b', 'c'],
\ ['x', 'y', 'z']
\ ]
let g:airline_powerline_fonts = 1
let g:airline_left_sep = ''
let g:airline_right_sep = ''
nmap <C-p> <Plug>AirlineSelectPrevTab
nmap <C-n> <Plug>AirlineSelectNextTab
nmap <C-d> :bd<Enter>
'''



[[plugins]]
repo = 'vim-airline/vim-airline-themes'
hook_add = '''
let g:airline_theme = 'jellybeans'
'''



[[plugins]]
repo = 'tpope/vim-fugitive'
# vim-airlineのために残す



# ===== 使わなくなったプラグイン =====
# [[plugins]]
# # CtrlP ファイル検索
# repo = 'ctrlpvim/ctrlp.vim'
#
#
# [[plugins]]
# # 文法check, 動作が重い
# repo = 'scrooloose/syntastic'
# hook_add = '''
# "let g:syntastic_python_checkers = ['pyflakes', 'pep8']
# "let g:syntastic_python_checkers = ['flake8']
# '''
#
#
# [[plugins]]
# repo = 'vim-scripts/timestamp.vim'
# hook_add = '''
# let g:timestamp_rep='%Y/%m/%d %H:%M:%S.'
# '''
#
#
# [[plugins]]
# repo = 'jiangmiao/auto-pairs'
# hook_add = '''
# let g:AutoPairs['<']='>'
# '''
#
#
# [[plugins]]
# repo = 'kana/vim-smartinput'
# on_event = 'InsertEnter'
# 削除がうまく機能しない
#
#
#
# [[plugins]]
# repo = 'Lokaltog/vim-easymotion'
# hook_add='''
# " <Leader>f{char} to move to {char}
# " map  <Leader>f <Plug>(easymotion-bd-f)
# " nmap <Leader>f <Plug>(easymotion-overwin-f)
#
# " s{char}{char} to move to {char}{char}
# nmap s <Plug>(easymotion-overwin-f2)
#
# " Move to line
# " map <Leader>L <Plug>(easymotion-bd-jk)
# " nmap <Leader>L <Plug>(easymotion-overwin-line)
#
# " Move to word
# map  <Space>w <Plug>(easymotion-bd-w)
# nmap <Space>w <Plug>(easymotion-overwin-w)
# '''
