[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/neocomplete.vim'

[[plugins]]
repo = 'Shougo/neosnippet.vim'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'scrooloose/nerdtree'
hook_add = '''
nnoremap <silent><Space>f :NERDTreeToggle<CR>
'''

[[plugins]]
repo = 'lervag/vimtex'

[[plugins]]
repo = 'thinca/vim-quickrun'
hook_add = '''
let g:quickrun_config = {
\   'outputter/buffer/split': ':right 1sp'
\ }
nnoremap <expr><silent> <C-c> quickrun#is_running() ? quickrun#sweep_sessions() : "\<C-c>"
'''

[[plugins]]
repo = 'tyru/caw.vim'
hook_add = '''
" 行の最初の文字の前にコメント文字をトグル
nmap <C-i> <Plug>(caw:hatpos:toggle)
vmap <C-i> <Plug>(caw:hatpos:toggle)
" 行頭にコメントをトグル
nmap <Leader>c <Plug>(caw:zeropos:toggle)
vmap <Leader>c <Plug>(caw:zeropos:toggle)
'''

[[plugins]]
repo = 'tyru/open-browser.vim'


# ===== 不要になったプラグイン =====
# [[plugins]]
# repo = 'ctrlpvim/ctrlp.vim'

# [[plugins]]
# repo = 'scrooloose/syntastic'
# hook_add = '''
# "let g:syntastic_python_checkers = ['pyflakes', 'pep8']
# "let g:syntastic_python_checkers = ['flake8']
# '''


# [[plugins]]
# repo = 'davidhalter/jedi-vim'

