[[plugins]]
repo = 'Shougo/dein.vim'


[[plugins]]
repo = 'scrooloose/nerdtree'
hook_add = '''
nnoremap <silent><Space>f :NERDTreeToggle<CR>
'''


[[plugins]]
repo = 'thinca/vim-quickrun'
hook_add = '''
let g:quickrun_config = {
\   'outputter/buffer/split': ':right 1sp'
\ }
nnoremap <expr><silent> <C-c> quickrun#is_running()
\ ? quickrun#sweep_sessions() : "\<C-c>"
'''


[[plugins]]
repo = 'tyru/caw.vim'
hook_add = '''
" ファイルタイプの自動検出を一旦offにする
" deinを使ったときにcaw.vimがうまく機能しなかったときにこれで直った
" (参考URL) http://d.hatena.ne.jp/wiredool/20120618/1340019962
filetype off
filetype plugin indent off

" 行の最初の文字の前にコメント文字をトグル
nmap <C-i> <Plug>(caw:hatpos:toggle)
vmap <C-i> <Plug>(caw:hatpos:toggle)
" 行頭にコメントをトグル
nmap <Leader>c <Plug>(caw:zeropos:toggle)
vmap <Leader>c <Plug>(caw:zeropos:toggle)

" ファイルタイプの自動検出を有効にする
filetype plugin indent on
'''


[[plugins]]
repo = 'vim-scripts/autodate.vim'
hook_add = '''
let g:autodate_format="%Y/%m/%d %H:%M:%S %Z"
'''


[[plugins]]
repo = 'tyru/open-browser.vim'
hook_add = '''
nmap gl <Plug>(openbrowser-smart-search)
vmap gl <Plug>(openbrowser-smart-search)
'''


[[plugins]]
repo = 'Townk/vim-autoclose'
hook_add='''
let g:AutoCloseProtectedRegions = ["Character"]
'''
# pythonで' "がうまく動かない?
# let g:AutoClosePairs = "() {} [] \" \'"
#


[[plugins]]
repo = 'w0rp/ale'
hook_add = '''
let g:ale_linters = {
\ 'python': ['flake8'],
\ }
let g:ale_sign_column_always = 1
let g:ale_lint_on_save = 1
let g:ale_lint_on_text_changed = 0
nnoremap <silent> <Space>m :ALEPrevious<CR>
nnoremap <silent> <Space>n :ALENext<CR>
let g:ale_statusline_format = ['⨉ %d', '⚠ %d', '⬥ ok']
'''


[[plugins]]
repo = 'vim-airline/vim-airline'
depends = ['vim-airline-themes', 'ale']
hook_add = '''
let g:airline#extensions#tabline#enabled = 1
let g:airline#extensions#ale#enabled = 1
let g:airline_powerline_fonts = 1
let g:airline_left_sep = ''
let g:airline_right_sep = ''
let g:airline#extensions#default#layout = [
\ ['a', 'b', 'c'],
\ ['x', 'y', 'z', 'error', 'warning']
\ ]
nmap <C-p> <Plug>AirlineSelectPrevTab
nmap <C-n> <Plug>AirlineSelectNextTab
nmap <C-d> :bd<Enter>
'''
# power-line fontのインストールが必要



[[plugins]]
repo = 'vim-airline/vim-airline-themes'
hook_add = '''
let g:airline_theme = 'jellybeans'
'''


[[plugins]]
repo = 'tpope/vim-fugitive'
# vim-airlineのために残す


[[plugins]]
repo = 'Yggdroot/indentLine'
hook_add = '''
let g:indentLine_color_term = 111
let g:indentLine_char = '¦'
'''


# Autocompletion settings
[[plugins]]
repo = 'prabirshrestha/async.vim'

[[plugins]]
repo = 'prabirshrestha/asyncomplete.vim'

[[plugins]]
repo = 'prabirshrestha/asyncomplete-lsp.vim'

[[plugins]]
repo = 'prabirshrestha/vim-lsp'
hook_add = '''
if empty(globpath(&rtp, 'autoload/lsp.vim'))
  finish
endif

function! s:on_lsp_buffer_enabled() abort
  setlocal omnifunc=lsp#complete
  setlocal signcolumn=yes
  nmap <buffer> gd <plug>(lsp-definition)
  nmap <buffer> <f2> <plug>(lsp-rename)
  " inoremap <expr> <cr> pumvisible() ? "\<c-y>\<cr>" : "\<cr>"
endfunction

augroup lsp_install
  au!
  autocmd User lsp_buffer_enabled call s:on_lsp_buffer_enabled()
augroup END
" command! LspDebug let lsp_log_verbose=1 | let lsp_log_file = expand('~/lsp.log')

let g:lsp_diagnostics_enabled = 0  " use ale instead
let g:lsp_diagnostics_echo_cursor = 0
let g:asyncomplete_auto_popup = 1
let g:asyncomplete_auto_completeopt = 0
let g:asyncomplete_popup_delay = 200
let g:lsp_text_edit_enabled = 1
'''

[[plugins]]
repo = 'mattn/vim-lsp-settings'
merged = 0

# Reference: https://mattn.kaoriya.net/software/vim/20191231213507.htm
[[plugins]]
repo = 'mattn/vim-lsp-icons'

[[plugins]]
repo = 'hrsh7th/vim-vsnip'

[[plugins]]
repo = 'hrsh7th/vim-vsnip-integ'

# Snippets
[[plugins]]
repo = 'thomasfaingnaert/vim-lsp-snippets'

[[plugins]]
repo = 'thomasfaingnaert/vim-lsp-neosnippet'

[[plugins]]
repo = 'Shougo/neosnippet.vim'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'


# ===== 使わなくなったプラグイン =====
# [[plugins]]
# # CtrlP ファイル検索
# repo = 'ctrlpvim/ctrlp.vim'
# [[plugins]]
# repo = 'jiangmiao/auto-pairs'
# hook_add = '''
# let g:AutoPairs['<']='>'
# '''
#
